### ISSUE TITLE
init.sh command terminates automatically.

### ISSUE THREAD

**Issue by sajet006** [cosmos/ethermint#601]
_System Info_ - branch: development, OS: Ubuntu 18.04.5 LTS

_Steps to reproduce_

1. git clone https://github.com/cosmos/ethermint.git
cd ethermint
make install or if by docker: make docker-build
2. ./init.sh
3. ethermintcli rest-server --laddr "tcp://localhost:8545" --unlock-key mykey --chain-id 8

_Expected behavior_ - docker build should install binaries without throwing any error & ./init.sh command should keep the command up & running, while running 3 step the test node should run.

_Actual Behaviour_
also while installing binaries by docker command(make docker-build) the following issue arises
<img width="878" alt="Untitled" src="https://user-images.githubusercontent.com/41197088/99374365-82634680-28e8-11eb-8259-7a26afd41201.png">

![Untitled (1)](https://user-images.githubusercontent.com/41197088/99374446-97d87080-28e8-11eb-9f67-7cac244f53dc.png)
<img width="286" alt="Untitled (2)" src="https://user-images.githubusercontent.com/41197088/99374588-ba6a8980-28e8-11eb-8d24-9cb0b0665cb2.png">

while running the ./init.sh command, it terminates automatically at the last line as mentioned below and doesn't keep on running

while running 3rd step in a separate command window the error comes

but when 3 Step is edited to ethermintcli rest-server --laddr "tcp://localhost:8545" --unlock-key mykey --chain-id ethermint-1, the error comes -:
<img width="1176" alt="Untitled (3)" src="https://user-images.githubusercontent.com/41197088/99374626-c8b8a580-28e8-11eb-8767-b2a78a579633.png">

**Comment by araskachoi** [comment]
Hello! Thank you for reaching out!

for this issue:
> also while installing binaries by docker command(make docker-build) the following issue arises
this has been fixed in this pr https://github.com/cosmos/ethermint/pull/598.
If you are having issues with the `make docker-build` command, you might be on a later commit of the repository and need to pull the latest to have the latest fixes.

> `ERROR: invalid chaind-id format: 8`
You cannot provide just an integer for the chain-id anymore. You will need to provide the keyword `ethermint` before the chain-id. So a properly formatted chain-id will look like `ethermint-8`

> but when 3 Step is edited to ethermintcli rest-server --laddr "tcp://localhost:8545" --unlock-key mykey --chain-id ethermint-1, the error comes -:

This error is coming out (`connect: connection refused`) because the ethermint daemon (ethermintd) process is not up and the rest-server cannot connect to the endpoint. You will need to have the daemon up and running in order for the `ethermintcli rest-server` command to work as intended.

----
 
I was not able to recreate any of these issues from a clean env. Could you try to use the latest commit on the `development` branch and run through these commands again? Please let us know if you have these issues again!

**Comment by Akkii4** [comment]
I have the latest commit pull of the development branch but still the issues remains the same ; however the docker installation didn't show the previous error of "invalid reference format" but now following
<img width="776" alt="image" src="https://user-images.githubusercontent.com/47569427/99780219-2e50a000-2b3c-11eb-995b-c80ba0f4a590.png">
also followed the commands as shown in the output command logs,
however the ./init.sh command still shows same error as mentioned above also the connect: connection refused error still persists

**Comment by araskachoi** [comment]
hello @Akkii4, glad the docker issue was fixed! I do not see the `./init.sh` error in the image above. do you think you can give an screenshot and steps to reproduce, as well as information about your system?

**Comment by sajet006** [comment]
The error was fixed. The issue was jq was not installed. Thanks for your help.
